### ISSUE TITLE
Source of the media.tar

### ISSUE THREAD

**Issue by razzeee** [hd-zero/hdzero-goggle#11]
What's the source/license of the media.tar? Why is it distributed like this?

**Comment by bkleiner** [comment]
they are libraries for different media functions directly from allwinner ([semi-official source](https://github.com/lindenis-org/lindenis-v536-softwinner/tree/master/eyesee-mpp))
i presume they are distributed like this because the build process in the original source's build process is incredibly convoluted.

i have started an attempt to sort that out [here](https://github.com/bkleiner/hdzero-goggle/tree/toolchain/lib/softwinner) some binary blobs remain however.

**Comment by razzeee** [comment]
Hrm, do you know which allwinner chip ended up in there? I only want to see if av1 is possible, but if it's not supported in hardware it's probably a no go. (I don't even know if they figured that out for their recent chips)

**Comment by bkleiner** [comment]
it's a allwinner v536, AV1 might be a little ambitious tho, in terms of video-codec support lifecycles that is basically brand new.

**Comment by razzeee** [comment]
I know, still the target with hardware support for av1 was 2021/22 if I remember right from talking with the devs on release in 2018. But I would have expected allwinner to not be on the leading edge according to my previous knowledge.

**Comment by razzeee** [comment]
Thanks!

Summary:
- av1 is impossible, as the chip is from 2019
- @bkleiner is working on a rework of the build process
