### ISSUE TITLE
Optional goggle power off at battery voltage

### ISSUE THREAD

**Issue by sunolfpv** [hd-zero/hdzero-goggle#31]
Optional menu setting under Power that turns goggle completely off at a given voltage or after no input signal detected for a given time. Not just a warning, but completely off. Idea is to save the screens from burn in or the battery past 3.0v, for example, if goggle is accidentally left on and unattended.

**Comment by bkleiner** [comment]
The oleds already automatically turn off when the goggles do not detect any more movement for a given time.
 
As far as i can tell, we have no means of _completely_ powering off the goggles, when i shutdown the linux running on the goggles the fans etc. are still running, so that wouldn't be all that helpful for not killing the battery.

**Comment by sunolfpv** [comment]
Thank you for the background. Closing as not relevant given OLED shut off and not being able to physically turn off from OS.
